import { GameDetailData } from '../../shared/models/game.model';

export const GAMES_DETAIL: GameDetailData[] = [
  {
    id: 'elden-ring',
    name: 'Elden Ring',
    shortName: 'ER',
    accentClass: 'er',
    developer: 'FromSoftware',
    releaseYear: 2022,
    genre: 'Action RPG',
    questCount: 214,
    loreCount: 891,
    followersCount: 12400,
    contributorsCount: 3200,
    topQuestTitle: 'Questline de Ranni, a Bruxa',
    topQuestSteps: 14,
    topQuestFollowers: 4800,
    lastActivityLabel: 'Atualizado há 2h',
    quests: [
      {
        id: 'er-q1',
        title: 'Questline de Ranni, a Bruxa',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        stepCount: 14,
        forkCount: 3,
        endingCount: 4,
        status: 'CANONICO',
        followers: 4800,
        author: null,
      },
      {
        id: 'er-q2',
        title: 'Questline de Millicent',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        stepCount: 9,
        forkCount: 2,
        endingCount: 2,
        status: 'CANONICO',
        followers: 2100,
        author: null,
      },
      {
        id: 'er-q3',
        title: 'Questline de Fia, a Guardiã dos Mortos',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        stepCount: 11,
        forkCount: 2,
        endingCount: 3,
        status: 'CONSOLIDADO',
        followers: 1700,
        author: null,
      },
      {
        id: 'er-q4',
        title: 'Teoria: Destino oculto de Melina',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        stepCount: 6,
        forkCount: 1,
        endingCount: 1,
        status: 'TEORIA',
        followers: 340,
        author: 'xcorpiiion',
      },
    ],
    featuredLore: [
      {
        id: 'er-l1',
        title: 'A Origem dos Dedos Dourados',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        category: 'TEORIA' as const,
        status: 'CANONICO',
        votes: 892,
        excerpt:
          'Os Dedos Dourados são fragmentos da Grande Vontade que guiam os Sem Graça rumo ao Elden Trono.',
        author: 'ds_wiki',
        readMinutes: 4,
        tags: [],
      },
      {
        id: 'er-l2',
        title: 'Marika e a Ruína da Ordem',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        category: 'NPC' as const,
        status: 'CONSOLIDADO',
        votes: 641,
        excerpt:
          'A deusa retirou o Fragmento Rúnico da Elden Ring, desencadeando a Ruína que fragmentou os semideuses.',
        author: 'ds_wiki',
        readMinutes: 6,
        tags: [],
      },
      {
        id: 'er-l3',
        title: 'Conexão entre Ranni e os Sem-Deus',
        gameId: 'elden-ring',
        gameName: 'Elden Ring',
        category: 'TEORIA' as const,
        status: 'TEORIA',
        votes: 218,
        excerpt:
          'Teoria sobre o papel de Ranni na queda dos antigos Sem-Deus e a execução do plano lunar.',
        author: 'theorycraft',
        readMinutes: 7,
        tags: [],
      },
    ],
  },
  {
    id: 'dark-souls-3',
    name: 'Dark Souls III',
    shortName: 'DS3',
    accentClass: 'ds3',
    developer: 'FromSoftware',
    releaseYear: 2016,
    genre: 'Action RPG',
    questCount: 98,
    loreCount: 412,
    followersCount: 5800,
    contributorsCount: 1400,
    topQuestTitle: 'Siegward de Catarina',
    topQuestSteps: 8,
    topQuestFollowers: 1200,
    lastActivityLabel: 'Atualizado há 1d',
    quests: [
      {
        id: 'ds3-q1',
        title: 'Questline de Siegward de Catarina',
        gameId: 'dark-souls-3',
        gameName: 'Dark Souls III',
        stepCount: 8,
        forkCount: 1,
        endingCount: 2,
        status: 'CANONICO',
        followers: 1200,
        author: null,
      },
    ],
    featuredLore: [
      {
        id: 'ds3-l1',
        title: 'Gwyn sabia do Oco desde o início',
        gameId: 'dark-souls-3',
        gameName: 'Dark Souls III',
        category: 'TEORIA' as const,
        status: 'TEORIA',
        votes: 99,
        excerpt:
          'Evidências nos arquivos de texto sugerem que Gwyn manipulou deliberadamente o ciclo de Vinculação do Fogo.',
        author: 'ds_wiki',
        readMinutes: 8,
        tags: [],
      },
    ],
  },
  {
    id: 'bloodborne',
    name: 'Bloodborne',
    shortName: 'BB',
    accentClass: 'bb',
    developer: 'FromSoftware',
    releaseYear: 2015,
    genre: 'Action RPG',
    questCount: 67,
    loreCount: 534,
    followersCount: 4200,
    contributorsCount: 980,
    topQuestTitle: 'A Boneca de Yharnam',
    topQuestSteps: 6,
    topQuestFollowers: 760,
    lastActivityLabel: 'Atualizado há 3d',
    quests: [
      {
        id: 'bb-q1',
        title: 'Questline de Eileen, a Corvina',
        gameId: 'bloodborne',
        gameName: 'Bloodborne',
        stepCount: 9,
        forkCount: 2,
        endingCount: 2,
        status: 'CANONICO',
        followers: 760,
        author: null,
      },
    ],
    featuredLore: [
      {
        id: 'bb-l1',
        title: 'O ciclo dos sonhos e Mergo',
        gameId: 'bloodborne',
        gameName: 'Bloodborne',
        category: 'NPC' as const,
        status: 'CONSOLIDADO',
        votes: 412,
        excerpt:
          'Mergo é um Grande Ser nascido do pesadelo, e a Ama de Mergo nunca para de chorar pois ele já está morto.',
        author: 'lore_bb',
        readMinutes: 4,
        tags: [],
      },
    ],
  },
  {
    id: 'lies-of-p',
    name: 'Lies of P',
    shortName: 'LoP',
    accentClass: 'lop',
    developer: 'Round8 Studio',
    releaseYear: 2023,
    genre: 'Soulslike',
    questCount: 31,
    loreCount: 89,
    followersCount: 1200,
    contributorsCount: 320,
    topQuestTitle: 'Sofia e o Coração',
    topQuestSteps: 7,
    topQuestFollowers: 510,
    lastActivityLabel: 'Atualizado há 5d',
    quests: [
      {
        id: 'lop-q1',
        title: 'Questline de Sofia e o Coração',
        gameId: 'lies-of-p',
        gameName: 'Lies of P',
        stepCount: 7,
        forkCount: 1,
        endingCount: 2,
        status: 'CANONICO',
        followers: 510,
        author: null,
      },
    ],
    featuredLore: [],
  },
  {
    id: 'lords-of-the-fallen',
    name: 'Lords of the Fallen',
    shortName: 'LotF',
    accentClass: 'lotf',
    developer: 'Hexworks',
    releaseYear: 2023,
    genre: 'Action RPG',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: 'Sem atividade',
    quests: [],
    featuredLore: [],
  },
];
