sonar.projectKey=xcorpiiion_souls-guide-front
sonar.organization=xcorpiiion

sonar.projectName=SoulGuide
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/main.ts

sonar.typescript.lcov.reportPaths=coverage/soulguide/lcov.info
sonar.javascript.lcov.reportPaths=coverage/soulguide/lcov.info

sonar.sourceEncoding=UTF-8
