import { GameSummary } from '../../shared/models/game.model';

export const GAMES_SUMMARY: GameSummary[] = [
  {
    id: 'elden-ring',
    name: 'Elden Ring',
    shortName: 'ER',
    accentClass: 'er',
    questCount: 8,
    loreCount: 3,
    followersCount: 312,
    contributorsCount: 48,
    topQuestTitle: 'Questline da Ranni',
    topQuestSteps: 24,
    topQuestFollowers: 312,
    lastActivityLabel: 'Atualizado há 2h',
  },
  {
    id: 'dark-souls-3',
    name: 'Dark Souls III',
    shortName: 'DS3',
    accentClass: 'ds3',
    questCount: 5,
    loreCount: 2,
    followersCount: 185,
    contributorsCount: 21,
    topQuestTitle: 'Siegward de Catarina',
    topQuestSteps: 8,
    topQuestFollowers: 97,
    lastActivityLabel: 'Atualizado há 1d',
  },
  {
    id: 'bloodborne',
    name: 'Bloodborne',
    shortName: 'BB',
    accentClass: 'bb',
    questCount: 3,
    loreCount: 2,
    followersCount: 140,
    contributorsCount: 15,
    topQuestTitle: 'A Boneca de Yharnam',
    topQuestSteps: 6,
    topQuestFollowers: 76,
    lastActivityLabel: 'Atualizado há 3d',
  },
  {
    id: 'lies-of-p',
    name: 'Lies of P',
    shortName: 'LoP',
    accentClass: 'lop',
    questCount: 2,
    loreCount: 0,
    followersCount: 51,
    contributorsCount: 8,
    topQuestTitle: 'Sofia e o Coração',
    topQuestSteps: 7,
    topQuestFollowers: 51,
    lastActivityLabel: 'Atualizado há 5d',
  },
  {
    id: 'lords-of-the-fallen',
    name: 'Lords of the Fallen',
    shortName: 'LotF',
    accentClass: 'lotf',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: 'Sem atividade',
  },
];
