import { QuestVersion } from '../../core/services/quest-version.service';

export const QUEST_HISTORY_MOCK: QuestVersion[] = [
  {
    versionNumber: 4,
    questId: 1,
    editedBy: { userId: 1, nickname: 'vincruz' },
    editedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    status: 'current',
    diff: {
      titleOld: null,
      titleNew: null,
      descriptionOld: 'Execute o Plano da Lua.',
      descriptionNew: 'Execute o Plano da Lua e liberte os Sem Graça.',
      statusOld: null,
      statusNew: null,
      nodesAdded: 3,
      nodesRemoved: 0,
    },
    revertVotes: 2,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: false,
    revertedBy: null,
    revertReason: null,
  },
  {
    versionNumber: 3,
    questId: 1,
    editedBy: { userId: 2, nickname: 'aldric_s' },
    editedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    status: 'active',
    diff: {
      titleOld: 'Questline da Bruxa',
      titleNew: 'Questline de Ranni, a Bruxa',
      descriptionOld: null,
      descriptionNew: null,
      statusOld: 'TEORIA',
      statusNew: 'CONSOLIDADO',
      nodesAdded: 0,
      nodesRemoved: 0,
    },
    revertVotes: 0,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: false,
    revertedBy: null,
    revertReason: null,
  },
  {
    versionNumber: 2,
    questId: 1,
    editedBy: { userId: 99, nickname: 'troll_xd' },
    editedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    status: 'reverted',
    diff: {
      titleOld: 'Questline de Ranni, a Bruxa',
      titleNew: 'aaaaaaaaaa lixo',
      descriptionOld: null,
      descriptionNew: null,
      statusOld: null,
      statusNew: null,
      nodesAdded: 0,
      nodesRemoved: 8,
    },
    revertVotes: 7,
    revertVotesNeeded: 5,
    userHasVoted: false,
    strikeIssued: true,
    revertReason: 'votes',
    revertedBy: 'sistema',
    revertedFromVersion: null,
  },
  {
    versionNumber: 1,
    questId: 1,
    editedBy: { userId: 1, nickname: 'vincruz' },
    editedAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    status: 'active',
    diff: {
      titleOld: null,
      titleNew: null,
      descriptionOld: null,
      descriptionNew: null,
      statusOld: null,
      statusNew: null,
      nodesAdded: 0,
      nodesRemoved: 0,
    },
    revertVotes: 0,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: false,
    revertedBy: null,
    revertReason: null,
  },
];
