import { QuestDetailData } from '../../shared/models/quest.model';

export const QUESTS_DETAIL: QuestDetailData[] = [
  {
    id: 'er-q1',
    title: 'Questline de Ranni, a Bruxa',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 7,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 4800,
    author: null,
    description:
      'Questline da semideusa Ranni, cujo objetivo é executar o Plano da Lua — libertar os Sem Graça do controle dos Grandes Seres.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Encontrar Ranni',
        sublabel: 'Torre de Ranni',
        description:
          'Vá até a Torre de Ranni no castelo de Caria e suba até o topo para encontrá-la. Ela só aparece à meia-noite.',
        location: 'Caria, Liurnia',
        tags: ['NPC', 'Torre de Ranni', 'noite'],
      },
      { id: 'n2', type: 'gateway', label: 'X' },
      {
        id: 'n3',
        type: 'task',
        label: 'Derrotar Loretta',
        sublabel: 'Catacomba',
        description:
          'Limpe a Catacomba de Ranni e derrote o Cavaleiro Fantasma Loretta para obter o espírito de Ranni.',
        location: 'Catacomba de Ranni',
        tags: ['boss', 'obrigatório'],
      },
      {
        id: 'n4',
        type: 'external-quest',
        label: 'Quest Blaidd',
        sublabel: 'Nó 3',
        description:
          'Antes de prosseguir, é necessário ter liberado Blaidd da Sellia. Esse ponto cruza com a questline dele.',
        linkedQuestId: 'er-q2',
        linkedQuestName: 'Questline do Blaidd',
        linkedNodeLabel: 'Nó 3 — Liberar da Sellia',
      },
      {
        id: 'n5',
        type: 'task',
        label: 'Entregar Espada',
        sublabel: 'Torre de Ranni',
        description:
          'Entregue a Espada Noctívaga para Ranni. Ambos os caminhos (via Loretta ou via Blaidd) convergem aqui.',
        location: 'Torre de Ranni',
        tags: ['item', 'Espada Noctívaga'],
      },
      {
        id: 'n6',
        type: 'end',
        label: 'Final A',
        sublabel: 'Ordem da Lua',
        description:
          'Ranni estabelece a Ordem da Lua — um mundo sem a influência dos Grandes Seres.',
        endingType: 'positive',
      },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3', label: 'via Loretta' },
      { id: 'e3', from: 'n2', to: 'n4', label: 'via Blaidd' },
      { id: 'e4', from: 'n3', to: 'n5' },
      { id: 'e5', from: 'n4', to: 'n5' },
      { id: 'e6', from: 'n5', to: 'n6' },
    ],
    relatedQuests: [
      {
        questId: 'er-q2',
        questTitle: 'Questline do Blaidd',
        npcInitials: 'BL',
        crossingNodeLabel: 'Quest Blaidd — Nó 3',
      },
      {
        questId: 'er-q3',
        questTitle: 'Questline de Millicent',
        npcInitials: 'ML',
        crossingNodeLabel: 'Entregar Espada',
      },
    ],
  },
  {
    id: 'er-q2',
    title: 'Questline do Blaidd',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 5,
    forkCount: 0,
    endingCount: 1,
    status: 'CANONICO',
    followers: 2300,
    author: 'vincruz',
    description:
      'O meio-lobo guardião de Ranni e sua tragédia inevitável — uma questline que termina sempre em sangue.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Encontrar Blaidd',
        sublabel: 'Mistwood',
        description:
          'Ouça o uivo na Floresta Nublada e toque o símbolo do dedo para convocar Blaidd.',
        location: 'Mistwood Ruins',
      },
      {
        id: 'n2',
        type: 'task',
        label: 'Liberar da Sellia',
        sublabel: 'Caelid',
        description: 'Ajude Blaidd a escapar da armadilha de Seluvis dentro do poço de Sellia.',
        location: 'Sellia, Caelid',
      },
      {
        id: 'n3',
        type: 'task',
        label: 'Batalha de Nokron',
        sublabel: 'Underground',
        description: 'Lute lado a lado com Blaidd contra o Chefe Mimic Tear para abrir Nokron.',
        location: 'Nokron',
        tags: ['boss', 'co-op'],
      },
      {
        id: 'n4',
        type: 'end',
        label: 'Tragédia Final',
        sublabel: 'Caria',
        description:
          'Após o sucesso de Ranni, Blaidd enlouquece por sua natureza de demispell e deve ser combatido.',
        endingType: 'tragic',
      },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4' },
    ],
    relatedQuests: [
      {
        questId: 'er-q1',
        questTitle: 'Questline de Ranni',
        npcInitials: 'RA',
        crossingNodeLabel: 'Quest Blaidd — Nó 3',
      },
    ],
  },
  {
    id: 'er-q3',
    title: 'Questline de Millicent',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 6,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 1900,
    author: null,
    description:
      'A filha de Malenia e a maldição da Podridão Escarlate — a questline mais emocionalmente pesada do jogo.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Encontrar Millicent',
        sublabel: 'Igreja de Caelid',
        description: 'Encontre Millicent na Igreja de Caelid e entregue a ela o Unguento de Ouro.',
        location: 'Igreja de Caelid',
      },
      {
        id: 'n2',
        type: 'task',
        label: 'Altus Plateau',
        sublabel: 'Leste de Altus',
        description: 'Reencontre Millicent nos campos de Altus após cruzar o Grand Lift of Dectus.',
        location: 'Altus Plateau',
      },
      {
        id: 'n3',
        type: 'task',
        label: 'Haligtree',
        sublabel: 'Elphael',
        description:
          'Ajude Millicent a derrotar suas irmãs em Elphael. Escolha protegê-la ou traí-la.',
        location: 'Elphael, Haligtree',
      },
      { id: 'n4', type: 'gateway', label: '?' },
      {
        id: 'n5',
        type: 'end',
        label: 'Redenção',
        sublabel: 'Broche de Malenia',
        description: 'Millicent aceita seu destino em paz — você recebe o Broche de Malenia.',
        endingType: 'neutral',
      },
      {
        id: 'n6',
        type: 'end',
        label: 'Traição',
        sublabel: 'Agulha de Rotten',
        description:
          'Millicent é sacrificada — você recebe a Agulha da Cura para remover a Chama da Fratura.',
        endingType: 'tragic',
      },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4' },
      { id: 'e4', from: 'n4', to: 'n5', label: 'proteger' },
      { id: 'e5', from: 'n4', to: 'n6', label: 'trair' },
    ],
    relatedQuests: [
      {
        questId: 'er-q1',
        questTitle: 'Questline de Ranni',
        npcInitials: 'RA',
        crossingNodeLabel: 'Entregar Espada',
      },
    ],
  },
  {
    id: 'bb-q1',
    title: 'Questline de Eileen the Crow',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 5,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 1400,
    author: null,
    description:
      'A caçadora que caça outros caçadores — um arco sobre a tragédia de quem enlouquece com a caça.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Encontrar Eileen',
        sublabel: 'Central Yharnam',
        description:
          'Encontre Eileen próximo ao poço de Central Yharnam e receba a missão de caçar caçadores.',
        location: 'Central Yharnam',
      },
      {
        id: 'n2',
        type: 'task',
        label: 'Derrotar Henryk',
        sublabel: 'Catedral Ward',
        description: 'Ajude Eileen a derrotar Henryk, o antigo parceiro que enlouqueceu.',
        location: 'Catedral Ward',
        tags: ['boss', 'obrigatório'],
      },
      { id: 'n3', type: 'gateway', label: '?' },
      {
        id: 'n4',
        type: 'end',
        label: 'Insígnia dos Corvos',
        sublabel: 'Sucesso',
        description: 'Eileen sobrevive e lhe entrega a Insígnia dos Caçadores Corvos.',
        endingType: 'positive',
      },
      {
        id: 'n5',
        type: 'end',
        label: 'Eileen cai',
        sublabel: 'Falha',
        description: 'Eileen morre no confronto com Gehrman antes que você a salve.',
        endingType: 'tragic',
      },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4', label: 'salvar a tempo' },
      { id: 'e4', from: 'n3', to: 'n5', label: 'chegar tarde' },
    ],
    relatedQuests: [],
  },
  {
    id: 'bb-q2',
    title: 'Investigação de Yharnam',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 4,
    forkCount: 0,
    endingCount: 3,
    status: 'CONSOLIDADO',
    followers: 980,
    author: 'lore_bb',
    description:
      'O arco principal da noite de caça e os três finais possíveis: aceitar, despertar ou ascender.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Explorar Yharnam',
        sublabel: 'Noite de caça',
        location: 'Yharnam',
      },
      {
        id: 'n2',
        type: 'task',
        label: 'Derrotar Mergo',
        sublabel: 'Pesadelo',
        location: 'Pesadelo da Metrópole',
      },
      { id: 'n3', type: 'gateway', label: '?' },
      { id: 'n4', type: 'end', label: 'Acordar', endingType: 'neutral' },
      { id: 'n5', type: 'end', label: 'Sacrifício', endingType: 'positive' },
      { id: 'n6', type: 'end', label: 'Ascensão', endingType: 'tragic' },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4', label: 'acordar' },
      { id: 'e4', from: 'n3', to: 'n5', label: 'sacrificar' },
      { id: 'e5', from: 'n3', to: 'n6', label: '3 terços de córdão' },
    ],
    relatedQuests: [],
  },
  {
    id: 'ds3-q1',
    title: 'Questline de Sirris do Luar',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    stepCount: 5,
    forkCount: 1,
    endingCount: 2,
    status: 'CONSOLIDADO',
    followers: 760,
    author: null,
    description:
      'A descendente de Hodrick e guardiã do Luar — questline que exige não trair o Covenant de Rosaria.',
    nodes: [
      { id: 'n0', type: 'start', label: 'início' },
      {
        id: 'n1',
        type: 'task',
        label: 'Encontrar Sirris',
        sublabel: 'Firelink Shrine',
        location: 'Firelink Shrine',
      },
      {
        id: 'n2',
        type: 'task',
        label: 'Salvar de Creighton',
        sublabel: 'Irithyll Bridge',
        location: 'Irithyll',
      },
      { id: 'n3', type: 'gateway', label: '?' },
      {
        id: 'n4',
        type: 'end',
        label: 'Armadura do Luar',
        description: 'Sirris completa seu juramento e lhe deixa a Armadura do Luar como presente.',
        endingType: 'positive',
      },
      {
        id: 'n5',
        type: 'end',
        label: 'Questline cancelada',
        description: 'Se você entrou em Rosaria, Sirris rompe relações e a questline é cancelada.',
        endingType: 'tragic',
      },
    ],
    edges: [
      { id: 'e0', from: 'n0', to: 'n1' },
      { id: 'e1', from: 'n1', to: 'n2' },
      { id: 'e2', from: 'n2', to: 'n3' },
      { id: 'e3', from: 'n3', to: 'n4', label: 'sem Rosaria' },
      { id: 'e4', from: 'n3', to: 'n5', label: 'entrou em Rosaria' },
    ],
    relatedQuests: [],
  },
];
