import { GameSummary } from '../../shared/models/game.model';
import { LoreSummary } from '../../shared/models/lore-article.model';
import { QuestSummary } from '../../shared/models/quest.model';

export const GAMES: GameSummary[] = [
  {
    id: '1',
    name: 'Elden Ring',
    shortName: 'ER',
    accentClass: 'accent-default',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: '—',
  },
  {
    id: '2',
    name: 'Dark Souls III',
    shortName: 'DS3',
    accentClass: 'accent-default',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: '—',
  },
  {
    id: '3',
    name: 'Bloodborne',
    shortName: 'BB',
    accentClass: 'accent-default',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: '—',
  },
  {
    id: '4',
    name: 'Lies of P',
    shortName: 'LoP',
    accentClass: 'accent-default',
    questCount: 0,
    loreCount: 0,
    followersCount: 0,
    contributorsCount: 0,
    topQuestTitle: null,
    topQuestSteps: null,
    topQuestFollowers: null,
    lastActivityLabel: '—',
  },
];

export const QUESTS: QuestSummary[] = [
  {
    id: 'er-q1',
    title: 'Questline de Ranni, a Bruxa',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 7,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 4800,
    author: null,
  },
  {
    id: 'er-q2',
    title: 'Questline do Blaidd',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 5,
    forkCount: 0,
    endingCount: 1,
    status: 'CANONICO',
    followers: 2300,
    author: 'vincruz',
  },
  {
    id: 'er-q3',
    title: 'Questline de Millicent',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 6,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 1900,
    author: null,
  },
  {
    id: 'bb-q1',
    title: 'Questline de Eileen the Crow',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 5,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 1400,
    author: null,
  },
  {
    id: 'ds3-q1',
    title: 'Questline de Sirris do Luar',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    stepCount: 5,
    forkCount: 1,
    endingCount: 2,
    status: 'CONSOLIDADO',
    followers: 760,
    author: null,
  },
  {
    id: 'q6',
    title: 'A Boneca de Yharnam',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 6,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 76,
    author: null,
  },
  {
    id: 'q7',
    title: 'Eileen, a Corvina',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 9,
    forkCount: 2,
    endingCount: 2,
    status: 'CONSOLIDADO',
    followers: 64,
    author: null,
  },
  {
    id: 'q8',
    title: 'Sofia e o Coração',
    gameId: 'lies-of-p',
    gameName: 'Lies of P',
    stepCount: 7,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 51,
    author: null,
  },
];

export const LORE: LoreSummary[] = [
  {
    id: 'ranni-plano-da-lua',
    title: 'Ranni, a Bruxa das Estrelas',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    category: 'CHARACTER',
    status: 'CANONICO',
    votes: 412,
    excerpt: 'Semideusa que abandonou seu destino divino para executar o Plano da Lua.',
    author: 'vincruz',
    readMinutes: 8,
    tags: [],
  },
  {
    id: 'gehrman-sonho-cacador',
    title: 'Gehrman e o Sonho do Caçador',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    category: 'CHARACTER',
    status: 'CANONICO',
    votes: 287,
    excerpt: 'O primeiro caçador e sua prisão voluntária no Sonho do Caçador.',
    author: 'lore_bb',
    readMinutes: 6,
    tags: [],
  },
  {
    id: 'runes-elden-ring-origem',
    title: 'O Elden Ring e os Grandes Runes',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    category: 'WORLD',
    status: 'TEORIA',
    votes: 203,
    excerpt: 'Teoria sobre a natureza do Elden Ring original e o que cada Grande Rune representa.',
    author: 'theorycraft',
    readMinutes: 11,
    tags: [],
  },
  {
    id: 'catedral-do-abismo',
    title: 'A Catedral do Abismo — Oolacile',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    category: 'WORLD',
    status: 'CONSOLIDADO',
    votes: 175,
    excerpt:
      'A queda de Oolacile e a corrupção de Manus revelam como o Abismo surge da humanidade.',
    author: 'ds_wiki',
    readMinutes: 7,
    tags: [],
  },
];
