import { Game } from '../../shared/models/game.model';
import { LoreSummary } from '../../shared/models/lore-article.model';
import { QuestSummary } from '../../shared/models/quest.model';

export const GAMES: Game[] = [
  { id: 'elden-ring', name: 'Elden Ring', shortName: 'ER' },
  { id: 'dark-souls-3', name: 'Dark Souls III', shortName: 'DS3' },
  { id: 'bloodborne', name: 'Bloodborne', shortName: 'BB' },
  { id: 'lies-of-p', name: 'Lies of P', shortName: 'LoP' },
  { id: 'lords-of-the-fallen', name: 'Lords of the Fallen', shortName: 'LotF' },
];

export const QUESTS: QuestSummary[] = [
  {
    id: 'q1',
    title: 'Quest da Ranni',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 24,
    forkCount: 3,
    endingCount: 4,
    status: 'CANONICO',
    followers: 312,
    author: null,
  },
  {
    id: 'q2',
    title: 'Quest do Blaidd',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 12,
    forkCount: 2,
    endingCount: 2,
    status: 'CANONICO',
    followers: 180,
    author: null,
  },
  {
    id: 'q3',
    title: 'Quest de Millicent',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    stepCount: 10,
    forkCount: 2,
    endingCount: 2,
    status: 'CANONICO',
    followers: 140,
    author: null,
  },
  {
    id: 'q4',
    title: 'Siegward de Catarina',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    stepCount: 8,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 97,
    author: null,
  },
  {
    id: 'q5',
    title: 'Aldrich e Gwyndolin',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    stepCount: 5,
    forkCount: 1,
    endingCount: 1,
    status: 'CONSOLIDADO',
    followers: 88,
    author: null,
  },
  {
    id: 'q6',
    title: 'A Boneca de Yharnam',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 6,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 76,
    author: null,
  },
  {
    id: 'q7',
    title: 'Eileen, a Corvina',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    stepCount: 9,
    forkCount: 2,
    endingCount: 2,
    status: 'CONSOLIDADO',
    followers: 64,
    author: null,
  },
  {
    id: 'q8',
    title: 'Sofia e o Coração',
    gameId: 'lies-of-p',
    gameName: 'Lies of P',
    stepCount: 7,
    forkCount: 1,
    endingCount: 2,
    status: 'CANONICO',
    followers: 51,
    author: null,
  },
];

export const LORE: LoreSummary[] = [
  {
    id: 'l1',
    title: 'A natureza da Lua Dourada',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    status: 'CANONICO',
    votes: 847,
    excerpt:
      'A Lua Dourada é a fonte do Elden Ring e da Grande Vontade, que governa os destinos dos Sem Graça.',
  },
  {
    id: 'l2',
    title: 'O ciclo dos sonhos e Mergo',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    status: 'CONSOLIDADO',
    votes: 412,
    excerpt:
      'Mergo é um Grande Ser nascido do pesadelo, e a Ama de Mergo nunca para de chorar pois ele já está morto.',
  },
  {
    id: 'l3',
    title: 'Marika e Radagon são a mesma',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    status: 'CONSOLIDADO',
    votes: 389,
    excerpt:
      'Marika e Radagon dividem o mesmo corpo — quando um governa, o outro aguarda dentro, cada um com vontades opostas.',
  },
  {
    id: 'l4',
    title: 'Ranni é a vilã real',
    gameId: 'elden-ring',
    gameName: 'Elden Ring',
    status: 'TEORIA',
    votes: 203,
    excerpt:
      'Teoria que defende que o plano de Ranni beneficia apenas ela própria, removendo a influência dos Grandes Seres.',
  },
  {
    id: 'l5',
    title: 'Gwyn sabia do Oco desde o início',
    gameId: 'dark-souls-3',
    gameName: 'Dark Souls III',
    status: 'TEORIA',
    votes: 99,
    excerpt:
      'Evidências nos arquivos de texto sugerem que Gwyn manipulou deliberadamente o ciclo de Vinculação do Fogo.',
  },
  {
    id: 'l6',
    title: 'A Grande Ameaça não é Mergo',
    gameId: 'bloodborne',
    gameName: 'Bloodborne',
    status: 'CONSOLIDADO',
    votes: 318,
    excerpt:
      'Iosefka e os outros Rom sugerem que a verdadeira ameaça ao mundo é a ascensão do Caçador como Grande Ser.',
  },
];
