import { LoreVersion } from '../../core/services/lore-version.service';

export const LORE_HISTORY_MOCK: LoreVersion[] = [
  {
    versionNumber: 3,
    loreId: 42,
    editedBy: { userId: 1, nickname: 'vincruz' },
    editedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    status: 'current',
    diff: {
      titleOld: null,
      titleNew: null,
      contentChanged: true,
      contentPreviewOld:
        'Os Sem Graça são aqueles que perderam a Graça — a luz dourada que guiava os escolhidos de Marika...',
      contentPreviewNew:
        'Os Sem Graça são aqueles que perderam a Graça — a luz dourada que guiava os escolhidos de Marika. Ranni concebeu um plano para libertá-los...',
    },
    revertVotes: 2,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: false,
    revertedBy: null,
    revertReason: null,
  },
  {
    versionNumber: 2,
    loreId: 42,
    editedBy: { userId: 99, nickname: 'troll_xd' },
    editedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    status: 'reverted',
    diff: {
      titleOld: 'A Ordem dos Sem Graça',
      titleNew: 'lixo lixo lixo',
      contentChanged: true,
      contentPreviewOld: 'Os Sem Graça são aqueles que perderam a Graça...',
      contentPreviewNew: 'asdfghjkl...',
    },
    revertVotes: 7,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: true,
    revertedBy: 'sistema',
    revertReason: 'votes',
  },
  {
    versionNumber: 1,
    loreId: 42,
    editedBy: { userId: 1, nickname: 'vincruz' },
    editedAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
    status: 'active',
    diff: {
      titleOld: null,
      titleNew: null,
      contentChanged: false,
      contentPreviewOld: null,
      contentPreviewNew: null,
    },
    revertVotes: 0,
    revertVotesNeeded: 5,
    userHasVoted: false,
    revertedFromVersion: null,
    strikeIssued: false,
    revertedBy: null,
    revertReason: null,
  },
];
